name: Build and Push image to ACR
on:
    push:
        branches:
            - main
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v2
            - name: Azure Login
              uses: azure/login@v2
              with:
                creds: ${{secrets.AZURE_CREDENTIALS}}
            - name: ACR login
              run: |
                az acr login --name mydockeracrregstry
            - name: Build and push the image
              run: |
                
                docker build -t mydockeracrregstry.azurecr.io/myapp:latest .
                docker push mydockeracrregstry.azurecr.io/myapp:latest